server:
  port: 8081

spring:
  application:
    name: service-msa-licenses
  security:
    user:
      name: ldh
      password: ldh

eureka:
  instance:
    hostname: localhost
  #  instance:
  #    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://ldh:ldh@localhost:8761/service-discovery-agent/eureka

