server:
  port: 8761

spring:
  application:
    name: service-discovery-agent
  security:
    user:
      name: ldh
      password: ldh

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhosgt:8761/eureka/

