spring:
  application:
    name: service-discovery-agent
  security:
    user:
      name: ldh
      password: ldh
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8761
  servlet:
    context-path: /service-discovery-agent

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://ldh:ldh@localhost:8761/service-discovery-agent/eureka

