server:
  port: 8888

spring:
#  profiles:
#    active: native
  application:
    name: service-config-agent
  security:
    user:
      name: ldh
      password: ldh

#  config:
#    activate:
#      on-profile: native    #?? ??? ??? ??? ???(?? ???)

  cloud:
    config:
      server:
        git:
          uri: https://github.com/ahdahddl/msa/
          username: ldh793692
          password: kaniza793692!
        encrypt:
            enabled: false
        native:
          search-locations: /Users/donghoonlee/IdeaProjects/msa/service-msa-cloud/src/main/resources,/Users/donghoonlee/IdeaProjects/msa/service-msa-licenses/src/main/resources


