server:
  port: 8080

spring:
  application:
    name: service-msa-cloud
#  profiles:
#    active: default
  security:
    user:
      name: ldh
      password: ldh

eureka:
  instance:
    hostname: localhost
#  instance:
#    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://ldh:ldh@localhost:8761/service-discovery-agent/eureka

