server:
  port: 8082

spring:
  application:
    name: service-msa-cloud
  profiles:
    active: default
  security:
    user:
      name: ldh
      password: ldh

eureka:
#  instance:
#    prefer-ip-address: false
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

